version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Pre-build started..."
      - ls -la

  build:
    commands:
      - echo "Build started..."
      - docker-compose config
      - echo "Build completed."

  post_build:
    commands:
      - echo "Preparing artifacts..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
